blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/yyDV3T4cwU
    about: Ask questions and discuss with other Ipspot community members 
  - name: Website
    url: https://openscilab.com/
    about: Check out our website for more information
